### ISSUE TITLE
Not loading il2cpp

### ISSUE THREAD

**Issue by slavadynasty** [MJx0/AndKittyInjector#6]
dlopen("libil2cpp.so"); return nullptr. how can I open the lib? I need to use with ByNameModding.

**Comment by slavadynasty** [comment]
I tried to open the lib using ByOpen, but I can't find "il2cpp_init" in it

**Comment by slavadynasty** [comment]
the problem is solved. it was necessary to modify macros
#define BNM_dlopen by_dlopen
#define BNM_dlsym by_dlsym
#define BNM_dlclose by_dlclose

**Comment by MJx0** [comment]
If you are using LD player then its likely because injected lib and il2cpp lib are in different namespace.
You can try the new released update which has overall improvements.

namespace for Houdini is here:
https://github.com/MJx0/AndKittyInjector/blob/cd567eb93380ef8b7eb5f99ee7ca6cc7c7f7ef34/AndKittyInjector/src/Injector/KittyInjector.cpp#L415

Though I recommend using third party library like xdl to deal with dl functions restrictions.

**Comment by slavadynasty** [comment]
The problem was that it was not possible to open the library via dlopen and I had to use ByOpen to solve it

> Though I recommend using third party library like xdl to deal with dl functions restrictions.
